# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db04cf371c6c76c3ee110b0f6094ce8d2e7cf43cfce24164904573ad9235215464f471bc2347aa62bebc3f0d6412c03038a23c4c19372a8c94a4fd30f22d5f3

test:
  secret_key_base: 0f01ed435bd63fa8e5b5142dcae4143c9fe73f83d6ccf007fa412efb99e3cbee9b39417cb7c10057eae06e8bae595aa586874415e0a4e295eb8c61fb319466a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
